name: Autoremove outdated CVEs

on:
  schedule:
    - cron: "10,15,20 * * * *"

jobs:
  auto-update-libs:
    uses: canonical/operator-workflows/.github/workflows/autoremove_trivyignore.yaml@feat/trivyignore
    secrets: inherit
