name: Autoremove outdated CVEs

on:
  schedule:
    - cron: "10,15,20 * * * *"

jobs:
  auto-update-libs:
    uses: canonical/operator-workflows/.github/workflows/auto_update_charm_libs.yaml@feat/trivyignore
    secrets: inherit
