name: Auto-update charm libraries

on:
  schedule:
<<<<<<< HEAD
    - cron: "30 * * * *"
=======
    - cron: "1 * * * *"
>>>>>>> main

jobs:
  auto-update-libs:
    uses: canonical/operator-workflows/.github/workflows/auto_update_charm_libs.yaml@feat/trivyignore
    secrets: inherit
