name: Auto-update charm libraries

on:
  schedule:
    - cron: "30 * * * *"

jobs:
  auto-update-libs:
    uses: canonical/operator-workflows/.github/workflows/auto_update_charm_libs.yaml@feat/trivyignore
    secrets: inherit
